<a href="https://colab.research.google.com/github/kushal2022/Tensorflow/blob/main/Basic_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print(tf.__version__)

2.18.0


In [8]:
# Initialization of tensors

x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

y = tf.constant([[1, 2, 3], [4, 5, 6]])
print(y)

z = tf.ones((3, 3))
print(z)

a = tf.zeros((2, 3))
print(a)

b = tf.eye(3)
print(b)

c = tf.random.normal((3, 3), mean=0, stddev=1)
print(c)

d = tf.random.uniform((1, 3), minval=2, maxval=3)
print(d)

e = tf.range(9)
print(e)

f = tf.range(start=1, limit=10, delta=2)
print(f)

f = tf.cast(f, dtype=tf.float64)
print(f)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.1999639   1.3241417   0.5103711 ]
 [ 0.15391815 -0.38304177  1.6077626 ]
 [ 1.2706829   0.09633251 -0.50179785]], shape=(3, 3), dtype=float32)
tf.Tensor([[2.6009946 2.344715  2.5132365]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [14]:
# Mathematical Operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
print(z)

z = x + y
print(z)

z = tf.subtract(x, y)
print(z)

z = x - y
print(z)

z = tf.divide(x, y)
print(z)

z = x / y
print(z)

z = tf.multiply(x, y)
print(z)

z = x * y
print(z)

z = tf.tensordot(x, y, axes=1)
print(z)

z = tf.reduce_sum(x * y, axis=0)
print(z)

z = x ** 5
print(z)

# Indexing
x = tf.random.normal((2, 3))
print(x)
print(x[0])
print(x[1])
print(x[0, :])

# Reshaping
x = tf.random.normal((2, 3))
print(x)
y = tf.reshape(x, (3, 2))
print(y)
z = tf.reshape(x, (-1, 2))
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-1.6431023   0.01302742 -0.2729962 ]
 [-0.3394521   0.5049355  -0.01737508]], shape=(2, 3), dtype=float32)
tf.Tensor([-1.6431023   0.01302742 -0.2729962 ], shape=(3,), dtype=float32)
tf.Tensor([-0.3394521   0.5049355  -0.01737508], shape=(3,), dtype=float32)
tf.Tensor([-1.6431023   0.01302742 -0.2729962 ], shape=(3,), dtype=float32)
tf.Tensor(
[[ 1.0452842  -0.17117214 -0.04154834]
 [-0.34158134  0.27833733 -0.6414792 ]], shape=(2,